---

- apt: name=apt-transport-https state=present

- name: Add sury public key
  apt_key:
    url: https://packages.sury.org/php/apt.gpg
    state: present

- apt_repository:
    repo: deb https://packages.sury.org/php/ stretch main
    state: present
    filename: sury

- name: Installation de PHP 5
  apt:
    name: php5.6
    state: present

- name: Installation des extensions
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php5.6-curl
    - php5.6-mysqlnd
    - php5.6-gd
    - php5.6-mbstring
    - php5.6-zip
    - php5.6-dom
    - php5.6-iconv
    - php5.6-simplexml
    - php5.6-xml
    - php5.6-json

- name: Activation des extensions
  shell: "phpenmod -v 5.6 {{ item }}"
  with_items:
    - curl
    - mysqli
    - zip
    - gd
    - mbstring
    - dom
    - iconv
    - simplexml
    - xml
    - json

- name: Installation de PHP 7
  apt:
    name: php7.0 ## Version en prod actuellement
    state: present

- name: Installation des extensions autres paquets PHP 7
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - php7.0-fpm
    - php7.0-curl
    - php7.0-mysqlnd
    - php7.0-xml
    - php7.0-zip

- name: Activation des extensions PHP 7
  shell: "phpenmod -v 7.0 {{ item }}"
  with_items:
    - curl
    - mysqli
    - xml
    - zip

- name: Version par défaut de PHP
  alternatives:
    name: php
    path: /usr/bin/php5.6

...